// Auto-generated by cmake/EmbedGuide.cmake — DO NOT EDIT.
// Edit assets/guide.txt and rebuild instead.
#pragma once
static const char* EMBEDDED_GUIDE_TXT = R"~~(
# OVERVIEW
- The map is a battlefield containing square tiles.
- Each tile can be one of 6 terrain types (see TERRAIN).
- You control Human to clear all Zombies on the map before the turn limit.
- Human acts first, then Zombies, then the Environment phase.
- Win: eliminate all zombies before the turn limit.
- Lose: your HP reaches 0, or the turn limit is exceeded.

# HUMAN
- Represented by the white square icon with blinking colorful border.
- The number in the middle is the remaining HP, the dots near the bottom are the remaining Stamina.
## Actions
- Actions of Human take Stamina; when Human runs out of Stamina, Human turn ends.
- Actions include moving and using weapons or tools, choose which action to be performed via the buttons on the right.
- For most actions (except Mine planting), there are directional arrows indicating possible direction choices.
- Those actions are considered to be performed only when you click on one of the tiles having the directional arrows
- You can end Human turn even before running out of Stamina.
- IMPORTANT: You cannot undo actions, so plan carefully before doing anything.
## Stamina
- At the start of each human turn, Stamina is given for Human to act.
- Stamina can either be rolled randomly from 1 to 6, or be fixed at a value.
- Moving on different terrains may costs different Stamina points.
- Using different weapons or tools may costs different Stamina points.
- You will lose 1 Stamina point in the next turn if you are bit by Sick Zombie.
- If you are Paralyzed, your Stamina in that turn is 0 and your turn ends automatically.
- If you pick up a Stamina potion from Loot drop, your Stamina is restored to 6 immediately.

# WEAPONS AND TOOLS
## Knife
- Melee weapon. Deals 1 damage to an adjacent Zombie.
- Costs 1 Stamina. No ammo required.
## Ice Pick
- Tool to break the Ice into Water.
- Costs 1 Stamina if Human is not Frozen, 2 Stamina otherwise. No ammo required.
## Pistol
- Ranged weapon. Accuracy drops with distance. Deals 1 damage if hit.
- Costs 1 Stamina. -1 ammo each time.
## Shotgun
- Fires in a 3-tile line, hitting all targets in the path. Deals 1 damage.
- Costs 1 Stamina. -1 ammo each time.
- Effect may be blocked by Wall tiles.
- Firing right at a Wall tile will destroy that Wall (into Dirt) and Human is knocked back by 1 step.
## Warp Bolt
- Exchanges 2 tiles via spacetime gates: one at the Human-standing tile, the other at the tile the bolt landing.
- The bolt landing on the furthest tile before blocked by Wall.
- Costs 1 Stamina. -1 ammo each time.
- Cause -1HP damage to entities involved in the exchange.
- If the bolt lands on the Human-standing tile, the extreme spacetime deformation causes immediate death to Human.
## Grenade
- Thrown randomly 1-6 tiles with a 1-turn fuse.
- Throwing may be blocked by Wall tiles, and this may cause Grenade to land on Human's tile and explode immediately.
- Costs 1 Stamina. -1 ammo each time.
- AoE: 3x3 if landed on Water or being Frozen under Ice, 5x5 otherwise.
- Damage: center tile -3HP, middle shell -2HP, outer shell -1HP.
- Knock back entities in middle shell.
- Effect may be blocked by Wall tiles.
- Can be blown by Windstorm.
## Molotov
- Thrown randomly 1–6 tiles. Creates a Fire tile on landing.
- Throwing may be blocked by Wall tiles, and this may cause Molotov to land on Human's tile.
- Costs 1 Stamina. -1 ammo each time.
## Mine
- Placed on the current tile.
- 1-tile blast radius. -1 ammo each time.
- Detonates when an entity steps on it; or triggered by Lightning, by Explosion, by Fire, by being shot by Pistol and Shotgun.

# ZOMBIE
- Represented by square icons with different colors (see the legends).
- The number in the middle is the remaining HP.
- Has tendency to move toward Human.
- Attacks: bite (orthogonal adjacent, -2HP), scratch (diagonal adjacent, -1HP).
- Attacking is the last action in each Zombie's turn.
- When a Zombie dies at a tile, it leave a Loot drop on the that tile.
## Clever
- 2 HP. Moves 1 tile per turn. Cannot attack after moving in Water.
- Can pick up Loot and use Weapons.
- Armed ones are marked with a small black triangle at the icon's top-right corner.
## Fast
- 2 HP. Moves 2 tiles per turn. Move 1 tile per turn in Water but can still attack after that.
## Exploding
- 3 HP. Detonates on death, dealing AoE damage.
- AoE: 1x1 if on Water or being Frozen under Ice, 3x3 otherwise.
- Damage when detonate: -1 HP, cause knocking back.
## Vampire
- 4 HP. Moves 1 tile per turn. Cannot attack after moving in Water.
- Steals your HP to heal itself via attacking you.
## Sick
- 2 HP. Moves 1 tile per turn. Cannot attack after moving in Water.
- Biting reduces your remaining number of turns by half and -1 HP in your next turn.
## Corruptor
- 1 HP. Moves 1 tile per turn. Cannot attack after moving in Water.
- On its turn, if any non-frozen loot drops are on 4 neighbouring (horizontal+vertical) tiles, it converts all of them into new Corruptors instead of moving.
- New Corruptors are fully independent and have the same ability.

# TERRAIN
## Dirt
- Standard tile. Passable.
- May transform into Water or Forest if there is Rain.
## Wall
- Blocks all movement and line-of-sight for ranged weapons.
- Blocks AoE of explosion and Shotgun.
- Can be destroyed by explosion and Shotgun.
## Water
- Passable, but costs 2 Stamina to enter.
- Conducts electricity to cause entities to be Paralyzed.
- Extinguishes Burned status.
- May become Ice under Blizzard.
- May evaporate into Dirt under Heatwave.
## Forest
- Passable.
- Become Fire if there is an adjacent Fire.
## Ice
- Passable. May cause unintentional sliding.
- Can be broken into Water by Ice Pick.
- Conducts electricity to cause entities to be Paralyzed.
- Becomes Water under Heatwave.
## Fire
- Cause entities stepping onto it to be Burned.
- Created by Molotov, or when Lightning strikes a Forest tile.
- Cause adjacent Forest to become Fire.
- Becomes Dirt under Rain and Blizzard.

# ENVIRONMENT EVENTS
## Clear sky
- Nothing happens.
## Windstorm
- Pushes entities, Grenades and Loot drops 1 tile in the wind direction if not blocked.
## Rain
- Extinguishes all Fire into Dirt and clears burning status on all entities.
- May transform Dirt into Water or Forest.
## Dark cloud
- Cover the whole map by a black color that lasts until the next Environment phase.
- Human can only see himself and the tiles enlightened by Fire.
## Lightning
- Strikes one or more random tiles.
- Entities hit take -1 HP damage.
- Striking on Forest causes Fire.
- Striking on Water or Ice cause spreading of electricity which causes paralysis.
## Heatwave
- Transforms Ice into Water, Water into Dirt.
- Cause Forest to conduct Fire faster.
## Blizzard
- May freeze Water into Ice.
- Extinguishes all Fire into Dirt and clears burning status on all entities.

# STATUS
## Burned
- Gets Burned when staying on a Fire tile.
- Loses 1 HP at the end of its turn if Burned is not resolved.
- Resolve: on Water, or there is Rain or Blizzard.
## Paralyzed
- Gets Paralyzed when staying on Water or Ice tiles which condctes electricity from Lightning.
- Cannot act for 1 turn.
## Frozen
- Get Frozen when stayin on Water while there is Blizzard that transforms Water into Ice.
- Cannot move, but can perform other actions.
- Human resolves by using Ice Pick.
- Frozen Loot drops cannot be picked up.

# MECHANISMS
## Knocked back
- Pushed back 1 tile by explosion or Shotgun.
- If blocked, causes Collision damage. 
## Pushed by Windstorm
- Pushed 1 tile in the wind direction if not blocked.
## Stunned
- When sliding on Ice tiles and collision with an obstruction.
- No damage, just end turn immediately.
## Wall-blocking
- AoE of explosions and ranged weapons are blocked by Wall tiles.
## Collision
- If blocked while being knocked back, the eneties in the collision take -1 HP damage each.

# LOOT DROPS
- Zombies drop loot when they die. Walk over a loot tile to pick it up.
- Multiple zombies dying on the same tile stack their drops (shown with a number badge).
- Loot frozen under Ice requires an Ice Pick to retrieve.
- Clever Zombie can pick loot.
- Loot drops can be transformed into Corruptor Zombies.
- Loot is destroyed by Fire, Lightning strike, explosion and Shotgun.
## Loot Types
- Junk: useless.
- PistolAmmo: +3 pistol rounds.
- StaminaPotion: restores Stamina to 6 for Human, adds 1 extra turn for Clever Zombie.
- HealthPotion: +2 HP.
- ShotgunAmmo: +1 shotgun shell.
- Grenade: +1 grenade.
- Molotov: +1 molotov cocktail.
- Mine: +1 land mine.
- WarpBolt: +1 warp charge — very rare.

# TIPS
## General
- Start on EASY to learn all the mechanics before bumping the difficulty.
- Kill Exploding zombies from a distance — their death blast can hurt you.
- Use Forest tiles for cover against Clever zombies with guns.
## Advanced
- Kite Fast zombies around obstacles to waste their extra move.
- Save Grenades for clustered groups — single-target use is inefficient.
- Stack kills on one turn to maximise multi-kill bonuses.
)~~";
