# EmbedFont.cmake
# Converts a binary font file to a C header using Python3 (fast, portable).
#
# Required variables (passed via -D):
#   FONT_INPUT   — absolute path to the .ttf file
#   FONT_OUTPUT  — absolute path to the generated header
#   FONT_VARNAME — C identifier prefix (e.g. font_noto_bold)

execute_process(
    COMMAND python3 -c "
import sys, os
src  = sys.argv[1]
dst  = sys.argv[2]
var  = sys.argv[3]
data = open(src,'rb').read()
n    = len(data)
cols = 16
lines = []
for i in range(0, n, cols):
    chunk = data[i:i+cols]
    lines.append('  ' + ', '.join(f'0x{b:02x}' for b in chunk))
body = ',\n'.join(lines)
with open(dst,'w') as f:
    f.write(f'// Auto-generated by cmake/EmbedFont.cmake -- DO NOT EDIT.\\n')
    f.write(f'// Source: {os.path.basename(src)}\\n')
    f.write(f'#pragma once\\n')
    f.write(f'static const unsigned int {var}_ttf_len = {n};\\n')
    f.write(f'static const unsigned char {var}_ttf[] = {{\\n{body}\\n}};\\n')
print(f'Embedded {n} bytes -> {dst}')
" "${FONT_INPUT}" "${FONT_OUTPUT}" "${FONT_VARNAME}"
    RESULT_VARIABLE PY_RESULT
)

if(NOT PY_RESULT EQUAL 0)
    message(FATAL_ERROR "EmbedFont: python3 failed for ${FONT_INPUT}")
endif()
