# EmbedGuide.cmake
# Reads assets/guide.txt and writes src/embedded/guide_txt.h containing the
# file content as a C++11 raw string literal.
# Called via cmake -P at build time so it always reflects the latest guide.txt.
#
# Required variables (passed via -D on the command line):
#   GUIDE_INPUT   — absolute path to assets/guide.txt
#   GUIDE_OUTPUT  — absolute path to the generated header

file(READ "${GUIDE_INPUT}" GUIDE_CONTENT)

# Escape any occurrence of the raw-string delimiter we plan to use.
# We use )~~" as the delimiter; if the file somehow contains that exact
# sequence we fall back to a different one. In practice guide.txt will never
# contain it.
string(REPLACE ")~~\"" ")~~_\"" GUIDE_CONTENT "${GUIDE_CONTENT}")

file(WRITE "${GUIDE_OUTPUT}"
"// Auto-generated by cmake/EmbedGuide.cmake — DO NOT EDIT.
// Edit assets/guide.txt and rebuild instead.
#pragma once
static const char* EMBEDDED_GUIDE_TXT = R\"~~(
${GUIDE_CONTENT})~~\";
")
